export const enum Characters {
  CARDINE_KOLLECKTA = "Cardine Kolleckta",
  DEQUES_APPLENTI = "Deques Applenti",
  FULTON_SUITCASE = "Fulton Suitcase",
  MORREY_CAARDMAN = "Morrey Caardman",
  POWER_CREEP = "Power Creep",
  SHUR_WEN_NA = "Shur Wen Na",
  CARDINAL_BAANZ = "Cardinal Baanz",
  FRIENDLY_ALIEN_LETTSTRADE = "Friendly Alien Lettstrade",
  PRITCHARD_LEFTFIELD = "Pritchard Leftfield",
  THE_CARD_SHARK = "The Card Shark",
  RARITTI_SIKARH = "Raritti Sikarh",
  SHAFILLE_DUCARTE = "Shafille Du Carte",
  PROTOR_VON_GRANPRIE = "Protor Von Granprie",
  GRELINE_ALCARTONE = "Greline Alcartone",
  CAPTIAN_CHETARR = "Captian Chetarr",
  DESTINE_DRAA = "Destine Draa",
  PRESSMASTER_1000_GTX_MK_II = "Pressmaster 1000 GTX MK II",
  PROXANNE_COUNTERFEIT_III = "Proxanne Counterfeit III",
  RAUL_SAWYER = "Raul Sawyer",
  SKILLIAN_TAUPEHT = "Skillian Taupeht",
  AARON_G = "Aaron G",
  EXALTIUS_THE_UNBEATABLE = "Exaltius the Unbeatable",
  MYSTERIOUS_ALIEN_F = "Mysterious Alien F",
}

export const enum StarterDeck {
  BLUELAKE_VILLAGE = "Bluelake Village",
  BROWNWALL_CITY = "Brownwall City",
  CHATEAU_HELBANE = "Chateau Helbane",
  GREENDEW_BAZAAR = "Greendew Bazaar",
  REDHILL_MERCENARIES = "Redhill Mercenaries",
  SAINTS_OF_WHITEHOLME = "Saints of Whiteholme",
  ANIMAL_FARM = "Animal Farm",
  FUTURE_PERFECT = "Future Perfect",
  GODS_AND_MYTHS = "Gods and Myths",
  MEGALOPOLIS = "Megalopolis",
  THE_ACADEMY = "The Academy",
  THE_GREAT_WAR = "The Great War",
}

export const enum BronzePromo {
  ELEMENTAL_BLADES = "Elemental Blades",
  LEAVE_IT_TO_BACKERS = "Leave it to Backers",
  LEGEND_OF_FINAL_BADASS = "Legend of Final Badass",
  THE_BACKER_BUNCH = "The Backer Bunch",
  ARGENT_SUPPORTERS = "Argent Supporters",
  BACKERS_IN_THE_HOUSE = "Backers in the House",
  HALLOWEEN_SPOOK_TACULAR = "Halloween Spook-tacular",
  WAR_OF_INDINES = "War of Indines",
  WORLD_OF_EARTHCRAFT = "World of Earth Craft",
  SEVEN_CARD_SLUGFEST = "7-Card Slugfest",
  ANANSI_AND_THE_BOX_OF_STORIES = "Anansi and the Box of Stories",
  SELLSWORDS = "Sellswords",
  FRAME_WARS_PILOTS = "Frame Wars: Pilots",
  HEROES_WANTED = "Heroes Wanted",
  RARITTI_SIKARH_SHAFILLE_DUCARTE = "Raritti Sikarh Shafille Du Carte",
  ELEMENTAL_GEM_POWER = "Elemental Gem Power",
  ESPER_X_HUMANS = "Esper X Humans",
  PROFESSOR_TREASURES_SECRET_SKY_CASTLE = "Professor Treasure's Secret Sky Castle",
  SEVENTH_CROSS_HEROES = "Seventh Cross Heroes",
  BSI_BACKER_SET_INVESTIGATION = "BSI: Backer Set Investigation",
  FUSION_CHAOS = "Fusion Chaos",
  WERE_BACK_A_STARTER_DECKS_STORY = "We're Back! A Starter Deck's Story",
  AEGIS_COMBINING_ROBOT_STRATEGY_GAME = "AEGIS: Combining Robot Strategy Game",
  BURGLE_BROS = "Burgle Bros.",
  GRUFF = "Gruff.",
  STREET_MASTERS = "Street Masters",
}

export const enum SilverPromo {
  BACKER_MEETS_WORLD = "Backer Meets World",
  PRINCESS_BLADE = "Princess' Blade",
  SEALED_VAULTS = "Sealed Vaults",
  ARGENT_VOTERS = "Argent Voters",
  BACKERS_IN_THE_MIDDLE = "Backers in the Middle",
  DEVASTION_OF_INDINES = "Devastion of Indines",
  WANDERING_WARRIORS = "Wandering Warriors",
  GRIMOIRE_SHUFFLE = "Grimoire Shuffle",
  MASTER_PLAN = "Master Plan",
  POWER_PLAY = "Power Play",
  VARIANT_SOULS = "Variant Souls",
  FRAME_WARS_FRAMES = "Frame Wars: Frames",
  NEUROSHIMA_HEX_3 = "Neuroshima Hex! 3.0",
  RED_HORIZON = "Red Horizon",
  MASTER_FUSION_GEMS = "Master Fusion Gems",
  BALLISTIC_REIGN = "Ballistic Reign",
  ESPER_X_ESPERS = "Esper X Espers",
  SEVENTH_CROSS_VILLAINS = "Seventh Cross Villains",
  BACK_TO_THE_PAST = "Back to the Past",
  DOUBLE_TROUBLE = "Double Trouble",
  FRESH_BACKERS_OF_BEL_AIR = "Fresh Backers of Bel-Air",
  DICE_THRONE = "Dice Throne",
  KAMIGAMI_BATTLES = "Kamigami Battles",
  MIDDARA = "Middara",
  THE_RED_DRAGON_INN = "The Red Dragon Inn",
}

export const enum GoldPromo {
  BACKERS_IN_CHARGE = "Backers in Charge",
  ELEMENTAL_DRAGON_LORDS = "Elemental Dragon Lords",
  MILLENNIUM_ACCESSORIES = "Millennium Accessories",
  ARGENT_CANDIDATES = "Argent Candidates",
  FATE_OF_INDINES = "Fate of Indines",
  EVERYBODY_LOVES_BACKERS = "Everybody Loves Backers",
  COMMEDIA_DEL_ARTE = "Commedia Del Arte",
  MYSTIC_EMPYREAN = "Mystic Empyrean",
  MAGE_WARS = "Mage Wars",
  TERRENE_ODSSEY = "Terrene Odssey",
  SELLSWORDS_OLYMPUS = "Sellswords Olympus",
  TOMB_TRADER = "Tomb Trader",
  TRIAL_OF_INDINES = "Trial of Indines",
  BREAKING_BACKERS = "Breaking Backers",
  EXALTIUS_SHOPPING_LIST = "Exaltius' Shopping List",
  HOT_CHICKS = "Hot Chicks",
  DOOMTOWN_RELOADED = "Doomtown Reloaded",
  NEAR_AND_FAR = "Near and Far",
  KILL_THE_OVERLORD = "Kill the Overlord",
  MONOLITH_ARENA = "Monolith Arena",
}

export const enum ExpansionPack {
  ONE_THOUSAND_AND_ONE_NIGHTS = "1001 Nights",
  ANVILICIOUS_ARRANGEMENTS = "Anvilicious Arrangements",
  BLACK_FLAGS_BLACK_WATERS = "Black Flags Black Waters",
  FISTS_OF_STEEL = "Fists of Steel",
  GNOMANS_LAND = "Gno-Mans Land",
  LIGHTNING_BUG = "Lightning Bug",
  OBARI_AS_HELL = "Obari As Hell",
  RUBBER_DUCKY_MAID_CRUSADERS_R = "Rubber Ducky Maid Crusaders R",
  SAMURAI_MOWDOWN = "Samurai Mowdown",
  SUNSET_STRIDERS = "Sunset Striders",
  SUPER_PLUMBER_BROS = "Super Plumber Bros.",
  FAST = "Fast",
  QUANTUM_JUMP = "Quantum Jump",
  SAVED_BY_THE_90S = "Saved by the 90's",
  THE_THOUSAND_PIXEL_CABINET = "The Thousand-Pixel Cabinet",
  UUURGH = "Uuurgh!",
  MYSTIC_THE_RECKONING = "Mystic: The Reckoning",
  BORED_GAMES = "Bored Games",
  GET_SCHOOLED = "Get Schooled!",
  MB_CARDBARD_STREET = "MB Cardbard Street",
  SHILLS_AND_SHILLS_INC = "Shills & Shills Inc.",
  SHOULDERS_OF_WAR = "Shoulders of War",
  SUPER_ZEROS_THEY_TRY = "Super Zeros (They… Try!)",
  XENO_X2_OVER_LEVELED = "Xeno X2: Over Leveled",
  CRAFTING_COUNTRY = "Crafting Country",
  PRINCESS_POWER = "Princess Power",
  FUTURE_PROOF = "Future Proof",

}

export const enum PremiumPack {
  AD_2400 = "AD 2400",
  CARDS_FROM_THE_CRYPT = "Cards From the Crypt",
  CARDS_MAGICA = "Cards Magica",
  CLOCKWORK_EMPIRE = "Clockwork Empire",
  LEGEND_OF_TANANANAH = "Legend of Tanananah",
  MOUSE_CARD = "Mouse Card",
  PANDORAS_BOX_OPENED = "Pandora's Box Opened",
  UNDERLORDS_OF_METROPOLITAM = "Underlords of Metropolitam",
  XENO_X_OVER = "Xeno X-Over",
  DEUS_REX_MACHINA = "Deus Rex Machina",
  DEVELOPMENTAL_ISSUES = "Developmental Issues",
  GAME_OF_RINGS = "Game of Rings",
  SHONEN_LEAP = "Shonen Leap",
  COME_ON_DOWN = "Come on Down!",
  FASTER = "Faster",
  ROUTE_TRIGGER = "Route Trigger",
  SHIN_RUBBER_DUCKY_MAID_CRUSADERS_R = "SHIN Rubber Ducky Maid Crusaders R",
  STAR_POWER = "Star Power",
  WSF_WORLD_SELLOUT_FEDERATION = "WSF (World Sellout Federation)",
  THE_ACCESSORY_STRIKES_BACK = "The Accessory Strikes Back",
  WORLD_WARRIORS = "World Warriors",
  KARTES_DES_JARES = "Kartes des Jares",
}

export const enum MasterPack {
  DOUBLE_O_SIX_PLUS_ONE = "006 Plus One",
  FANTASY_FINALE_MCLXVH_2 = "Fantasy Finale MCLXVH-2",
  GALACTIC_CABOOSE = "Galactic Caboose",
  HELL_TO_PAY = "Hell to Pay",
  M_N_M = "M.N.M.",
  MILLENNIUM_MASTERS = "Millennium Masters",
  SYMPHONY_OF_DESTRUCTION = "Symphony of Destruction",
  VEX_CARDS_OF_HATE = "Vex: Cards of Hate",
  PENNY_DREADFUL = "Penny Dreadful",
  THE_ULTIMATE_STEEL_COOK = "The Ultimate Steel Cook",
  ULTIMATE_KAIJU_THROWDOWN = "Ultimate Kaiju Throwdown",
  ELDRITCH_ENTERTAINMENT_GROUP = "Eldritch Entertainment Group",
  RETURN_OF_THE_DRUID_KINGS = "Return of the Druid Kings",
  TCG_LLUMINATI = "TCG-lluminati",
  THEY_CAME_FROM_SPACE = "They Came From Space",
  THE_SPORTS_SET = "The Sports Set",
  CARDCEPT = "Cardcept",
  CORE_SET_II = "Core Set II",
  MONSTER_GIRLS = "Monster Girls",
  OKIE_DOKIE_LITERATURE_CLUB = "Okie Dokie: Literature Club!",
  TOY_TALES = "Toy Tales",
  FAST_3 = "Fast 3",
  REALM_OF_SHADOWS = "Realm of Shadows",
  BROKINS_BEST = "Bro'kin's Best",
}
