import { ExpansionName, Expansion } from "./models";

export const expansions: Expansion[] = [
  {
    name: ExpansionName.BASE_GAME,
    order: 0,
    characters: [
      "Cardine Kolleckta",
      "Deques Applenti",
      "Fulton Suitcase",
      "Morrey Caardman",
      "Power Creep",
      "Shur Wen Na",
    ],
    starterDecks: [
      "Bluelake Village",
      "Brownwall City",
      "Chateau Helbane",
      "Greendew Bazaar",
      "Redhill Mercenaries",
      "Saints of Whiteholme",
    ],
    bronzePromos: [
      "Elemental Blades",
      "Leave it to Backers",
      "Legend of Final Badass",
      "The Backer Bunch",
    ],
    silverPromos: ["Backer Meets World", "Princess' Blade", "Sealed Vaults"],
    goldPromos: [
      "Backers in Charge",
      "Elemental Dragon Lords",
      "Millennium Accessories",
    ],
    expansionPacks: [
      "1001 Nights",
      "Anvilicious Arrangements",
      "Black Flags, Black Waters",
      "Fists of Steel",
      "Gno-Mans Land",
      "Lightning Bug",
      "Obari As Hell",
      "Rubber Ducky Maid Crusaders R",
      "Samurai Mowdown",
      "Sunset Striders",
      "Super Plumber Bros.",
    ],
    premiumPacks: [
      "AD 2400",
      "Cards From the Crypt",
      "Cards Magica",
      "Clockwork Empire",
      "Legend of Tanananah",
      "Mouse Card",
      "Pandora's Box Opened",
      "Underlords of Metropolitam",
      "Xeno X-Over",
    ],
    masterPacks: [
      "006 Plus One",
      "Fantasy Finale MCLXVH-2",
      "Galactic Caboose",
      "Hell to Pay",
      "M.N.M.",
      "Millennium Masters",
      "Symphony of Destruction",
      "Vex: Cards of Hate",
    ],
  },
  {
    name: ExpansionName.SET_ROATION,
    order: 1,
    characters: [
      "Cardinal Baanz",
      "Friendly Alien Lettstrade",
      "Pritchard Leftfield",
      "The Card Shark",
    ],
    starterDecks: [
      "Animal Farm",
      "Future Perfect",
      "Gods and Myths",
      "Megalopolis",
      "The Academy",
      "The Great War",
    ],
    bronzePromos: [
      "Argent Supporters",
      "Backers in the House",
      "Halloween Spook-tacular",
      "War of Indines",
      "World of EarthCraft",
    ],
    silverPromos: [
      "Argent Voters",
      "Backers in the Middle",
      "Devastion of Indines",
      "Wandering Warriors",
    ],
    goldPromos: [
      "Argent Candidates",
      "Fate of Indines",
      "Everybody Loves Backers",
    ],
    expansionPacks: [
      "Fast",
      "Quantum Jump",
      "Saved by the 90's",
      "The Thousand-Pixel Cabinet",
      "Uuurgh!",
    ],
    premiumPacks: [
      "Deus Rex Machina",
      "Developmental Issues",
      "Game of Rings",
      "Shonen Leap",
    ],
    masterPacks: [
      "Penny Dreadful",
      "The Ultimate Steel Cook",
      "Ultimate Kaiju Throwdown",
    ],
  },
  {
    name: ExpansionName.CROSSOVER,
    order: 2,
    characters: [],
    starterDecks: [],
    bronzePromos: [
      "7-Card Slugfest",
      "Anansi and the Box of Stories",
      "Sellswords",
    ],
    silverPromos: [
      "Grimoire Shuffle",
      "Master Plan",
      "Power Play",
      "Variant Souls",
    ],
    goldPromos: ["Commedia Del Arte", "Mystic Empyrean"],
    expansionPacks: [],
    premiumPacks: [],
    masterPacks: [],
  },
  {
    name: ExpansionName.SPONSORS,
    order: 3,
    characters: [],
    starterDecks: [],
    bronzePromos: ["Frame Wars: Pilots", "Heroes Wanted"],
    silverPromos: ["Frame Wars: Frames", "Neuroshima Hex! 3.0", "Red Horizon"],
    goldPromos: ["Mage Wars", "Terrene Odssey"],
    expansionPacks: [],
    premiumPacks: [],
    masterPacks: [],
  },
  {
    name: ExpansionName.FUSION_CHAOS,
    order: 4,
    characters: ["Raritti Sikarh", "Shafille DuCarte"],
    starterDecks: [],
    bronzePromos: ["Elemental Gem Power"],
    silverPromos: ["Master Fusion Gems"],
    goldPromos: [],
    expansionPacks: [],
    premiumPacks: [],
    masterPacks: [],
  },
  {
    name: ExpansionName.FINAL_BOSSES,
    order: 5,
    characters: [],
    starterDecks: [],
    bronzePromos: [],
    silverPromos: [],
    goldPromos: [],
    expansionPacks: [],
    premiumPacks: [],
    masterPacks: [
      "Eldritch Entertainment Group",
      "Return of the Druid Kings",
      "TCG-lluminati",
      "They Came From Space",
    ],
  },
  {
    name: ExpansionName.FUTURES,
    order: 6,
    characters: [],
    starterDecks: [],
    bronzePromos: [
      "Esper X Humans",
      "Professor Treasure's Secret Sky Castle",
      "Seventh Cross Heroes",
    ],
    silverPromos: [
      "Ballistic Reign",
      "Esper X Espers",
      "Seventh Cross Villains",
    ],
    goldPromos: ["Sellswords Olympus", "Tomb Trader", "Trial of Indines"],
    expansionPacks: [],
    premiumPacks: [],
    masterPacks: [],
  },
  {
    name: ExpansionName.PROFESSIONALS,
    order: 7,
    characters: ["Protor Von Granprie", "Greline Alcartone"],
    starterDecks: [],
    bronzePromos: [],
    silverPromos: [],
    goldPromos: [],
    expansionPacks: ["Mystic: The Reckoning"],
    premiumPacks: [],
    masterPacks: ["The Sports Set"],
  },
].sort((a, b) => a.order - b.order);
